name: getit_ui
description: Getit - Shopping Lists
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.4
  provider: ^6.0.3
  logger: ^1.1.0
  google_sign_in: ^5.4.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
